<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="11" passed="9">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="15804" started-at="2015-05-10T00:08:38Z" finished-at="2015-05-10T00:08:54Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="15804" started-at="2015-05-10T00:08:38Z" finished-at="2015-05-10T00:08:54Z">
      <class name="com.FCI.SWE.Services.ServiceTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.FCI.SWE.Services.ServiceTest@5636e34]" name="setUp" is-config="true" duration-ms="406" started-at="2015-05-09T17:08:38Z" finished-at="2015-05-09T17:08:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="AcceptService()[pri:0, instance:com.FCI.SWE.Services.ServiceTest@5636e34]" name="AcceptService" duration-ms="13091" started-at="2015-05-09T17:08:38Z" finished-at="2015-05-09T17:08:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [fail] but found [OK]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [fail] but found [OK]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.FCI.SWE.Services.ServiceTest.AcceptService(ServiceTest.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:352)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:347)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AcceptService -->
        <test-method status="PASS" signature="createpage()[pri:0, instance:com.FCI.SWE.Services.ServiceTest@5636e34]" name="createpage" duration-ms="578" started-at="2015-05-09T17:08:52Z" finished-at="2015-05-09T17:08:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createpage -->
        <test-method status="FAIL" signature="displaypost()[pri:0, instance:com.FCI.SWE.Services.ServiceTest@5636e34]" name="displaypost" duration-ms="63" started-at="2015-05-09T17:08:52Z" finished-at="2015-05-09T17:08:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [["e","e","e","e"]] but found [["e","e","e","e"]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [["e","e","e","e"]] but found [["e","e","e","e"]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at com.FCI.SWE.Services.ServiceTest.displaypost(ServiceTest.java:188)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:352)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:347)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- displaypost -->
        <test-method status="PASS" signature="hgService()[pri:0, instance:com.FCI.SWE.Services.ServiceTest@5636e34]" name="hgService" duration-ms="47" started-at="2015-05-09T17:08:52Z" finished-at="2015-05-09T17:08:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- hgService -->
        <test-method status="PASS" signature="likepages()[pri:0, instance:com.FCI.SWE.Services.ServiceTest@5636e34]" name="likepages" duration-ms="94" started-at="2015-05-09T17:08:52Z" finished-at="2015-05-09T17:08:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- likepages -->
        <test-method status="PASS" signature="likeposts()[pri:0, instance:com.FCI.SWE.Services.ServiceTest@5636e34]" name="likeposts" duration-ms="221" started-at="2015-05-09T17:08:52Z" finished-at="2015-05-09T17:08:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- likeposts -->
        <test-method status="PASS" signature="loginService()[pri:0, instance:com.FCI.SWE.Services.ServiceTest@5636e34]" name="loginService" duration-ms="186" started-at="2015-05-09T17:08:53Z" finished-at="2015-05-09T17:08:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginService -->
        <test-method status="PASS" signature="mpost()[pri:0, instance:com.FCI.SWE.Services.ServiceTest@5636e34]" name="mpost" duration-ms="63" started-at="2015-05-09T17:08:53Z" finished-at="2015-05-09T17:08:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mpost -->
        <test-method status="PASS" signature="registrationServiceStringStringString()[pri:0, instance:com.FCI.SWE.Services.ServiceTest@5636e34]" name="registrationServiceStringStringString" duration-ms="125" started-at="2015-05-09T17:08:53Z" finished-at="2015-05-09T17:08:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registrationServiceStringStringString -->
        <test-method status="PASS" signature="searchService()[pri:0, instance:com.FCI.SWE.Services.ServiceTest@5636e34]" name="searchService" duration-ms="47" started-at="2015-05-09T17:08:53Z" finished-at="2015-05-09T17:08:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchService -->
        <test-method status="PASS" signature="sendMsg()[pri:0, instance:com.FCI.SWE.Services.ServiceTest@5636e34]" name="sendMsg" duration-ms="62" started-at="2015-05-09T17:08:53Z" finished-at="2015-05-09T17:08:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sendMsg -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.FCI.SWE.Services.ServiceTest@5636e34]" name="tearDown" is-config="true" duration-ms="453" started-at="2015-05-09T17:08:53Z" finished-at="2015-05-09T17:08:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.FCI.SWE.Services.ServiceTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
